// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie_details.proto
// Protobuf Java Version: 4.30.0

package protos;

public final class MovieDetailsProto {
  private MovieDetailsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      MovieDetailsProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protos.Genre}
   */
  public enum Genre
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACTION = 0;</code>
     */
    ACTION(0),
    /**
     * <code>COMEDY = 1;</code>
     */
    COMEDY(1),
    /**
     * <code>DRAMA = 2;</code>
     */
    DRAMA(2),
    /**
     * <code>HORROR = 3;</code>
     */
    HORROR(3),
    /**
     * <code>ROMANCE = 4;</code>
     */
    ROMANCE(4),
    /**
     * <code>THRILLER = 5;</code>
     */
    THRILLER(5),
    /**
     * <code>ADVENTURE = 6;</code>
     */
    ADVENTURE(6),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        Genre.class.getName());
    }
    /**
     * <code>ACTION = 0;</code>
     */
    public static final int ACTION_VALUE = 0;
    /**
     * <code>COMEDY = 1;</code>
     */
    public static final int COMEDY_VALUE = 1;
    /**
     * <code>DRAMA = 2;</code>
     */
    public static final int DRAMA_VALUE = 2;
    /**
     * <code>HORROR = 3;</code>
     */
    public static final int HORROR_VALUE = 3;
    /**
     * <code>ROMANCE = 4;</code>
     */
    public static final int ROMANCE_VALUE = 4;
    /**
     * <code>THRILLER = 5;</code>
     */
    public static final int THRILLER_VALUE = 5;
    /**
     * <code>ADVENTURE = 6;</code>
     */
    public static final int ADVENTURE_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Genre valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Genre forNumber(int value) {
      switch (value) {
        case 0: return ACTION;
        case 1: return COMEDY;
        case 2: return DRAMA;
        case 3: return HORROR;
        case 4: return ROMANCE;
        case 5: return THRILLER;
        case 6: return ADVENTURE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Genre>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Genre> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Genre>() {
            public Genre findValueByNumber(int number) {
              return Genre.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protos.MovieDetailsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Genre[] VALUES = values();

    public static Genre valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Genre(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protos.Genre)
  }

  public interface MovieDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.MovieDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 movieId = 1;</code>
     * @return The movieId.
     */
    long getMovieId();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string director = 3;</code>
     * @return The director.
     */
    java.lang.String getDirector();
    /**
     * <code>string director = 3;</code>
     * @return The bytes for director.
     */
    com.google.protobuf.ByteString
        getDirectorBytes();

    /**
     * <code>int64 release_year = 4;</code>
     * @return The releaseYear.
     */
    long getReleaseYear();

    /**
     * <code>repeated string genre = 5;</code>
     * @return A list containing the genre.
     */
    java.util.List<java.lang.String>
        getGenreList();
    /**
     * <code>repeated string genre = 5;</code>
     * @return The count of genre.
     */
    int getGenreCount();
    /**
     * <code>repeated string genre = 5;</code>
     * @param index The index of the element to return.
     * @return The genre at the given index.
     */
    java.lang.String getGenre(int index);
    /**
     * <code>repeated string genre = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the genre at the given index.
     */
    com.google.protobuf.ByteString
        getGenreBytes(int index);

    /**
     * <code>string rating = 6;</code>
     * @return The rating.
     */
    java.lang.String getRating();
    /**
     * <code>string rating = 6;</code>
     * @return The bytes for rating.
     */
    com.google.protobuf.ByteString
        getRatingBytes();

    /**
     * <code>string description = 7;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 7;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    java.util.List<protos.MovieDetailsProto.Cast> 
        getCastList();
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    protos.MovieDetailsProto.Cast getCast(int index);
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    int getCastCount();
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    java.util.List<? extends protos.MovieDetailsProto.CastOrBuilder> 
        getCastOrBuilderList();
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    protos.MovieDetailsProto.CastOrBuilder getCastOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.MovieDetails}
   */
  public static final class MovieDetails extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.MovieDetails)
      MovieDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        MovieDetails.class.getName());
    }
    // Use MovieDetails.newBuilder() to construct.
    private MovieDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MovieDetails() {
      title_ = "";
      director_ = "";
      genre_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      rating_ = "";
      description_ = "";
      cast_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.MovieDetailsProto.internal_static_protos_MovieDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.MovieDetailsProto.internal_static_protos_MovieDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.MovieDetailsProto.MovieDetails.class, protos.MovieDetailsProto.MovieDetails.Builder.class);
    }

    public static final int MOVIEID_FIELD_NUMBER = 1;
    private long movieId_ = 0L;
    /**
     * <code>int64 movieId = 1;</code>
     * @return The movieId.
     */
    @java.lang.Override
    public long getMovieId() {
      return movieId_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTOR_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object director_ = "";
    /**
     * <code>string director = 3;</code>
     * @return The director.
     */
    @java.lang.Override
    public java.lang.String getDirector() {
      java.lang.Object ref = director_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        director_ = s;
        return s;
      }
    }
    /**
     * <code>string director = 3;</code>
     * @return The bytes for director.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDirectorBytes() {
      java.lang.Object ref = director_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        director_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELEASE_YEAR_FIELD_NUMBER = 4;
    private long releaseYear_ = 0L;
    /**
     * <code>int64 release_year = 4;</code>
     * @return The releaseYear.
     */
    @java.lang.Override
    public long getReleaseYear() {
      return releaseYear_;
    }

    public static final int GENRE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList genre_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string genre = 5;</code>
     * @return A list containing the genre.
     */
    public com.google.protobuf.ProtocolStringList
        getGenreList() {
      return genre_;
    }
    /**
     * <code>repeated string genre = 5;</code>
     * @return The count of genre.
     */
    public int getGenreCount() {
      return genre_.size();
    }
    /**
     * <code>repeated string genre = 5;</code>
     * @param index The index of the element to return.
     * @return The genre at the given index.
     */
    public java.lang.String getGenre(int index) {
      return genre_.get(index);
    }
    /**
     * <code>repeated string genre = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the genre at the given index.
     */
    public com.google.protobuf.ByteString
        getGenreBytes(int index) {
      return genre_.getByteString(index);
    }

    public static final int RATING_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rating_ = "";
    /**
     * <code>string rating = 6;</code>
     * @return The rating.
     */
    @java.lang.Override
    public java.lang.String getRating() {
      java.lang.Object ref = rating_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rating_ = s;
        return s;
      }
    }
    /**
     * <code>string rating = 6;</code>
     * @return The bytes for rating.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRatingBytes() {
      java.lang.Object ref = rating_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rating_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 7;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 7;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAST_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private java.util.List<protos.MovieDetailsProto.Cast> cast_;
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    @java.lang.Override
    public java.util.List<protos.MovieDetailsProto.Cast> getCastList() {
      return cast_;
    }
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protos.MovieDetailsProto.CastOrBuilder> 
        getCastOrBuilderList() {
      return cast_;
    }
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    @java.lang.Override
    public int getCastCount() {
      return cast_.size();
    }
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    @java.lang.Override
    public protos.MovieDetailsProto.Cast getCast(int index) {
      return cast_.get(index);
    }
    /**
     * <code>repeated .protos.Cast cast = 8;</code>
     */
    @java.lang.Override
    public protos.MovieDetailsProto.CastOrBuilder getCastOrBuilder(
        int index) {
      return cast_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (movieId_ != 0L) {
        output.writeInt64(1, movieId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(director_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, director_);
      }
      if (releaseYear_ != 0L) {
        output.writeInt64(4, releaseYear_);
      }
      for (int i = 0; i < genre_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, genre_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rating_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, rating_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, description_);
      }
      for (int i = 0; i < cast_.size(); i++) {
        output.writeMessage(8, cast_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (movieId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, movieId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(director_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, director_);
      }
      if (releaseYear_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, releaseYear_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < genre_.size(); i++) {
          dataSize += computeStringSizeNoTag(genre_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getGenreList().size();
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rating_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, rating_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, description_);
      }
      for (int i = 0; i < cast_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, cast_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.MovieDetailsProto.MovieDetails)) {
        return super.equals(obj);
      }
      protos.MovieDetailsProto.MovieDetails other = (protos.MovieDetailsProto.MovieDetails) obj;

      if (getMovieId()
          != other.getMovieId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getDirector()
          .equals(other.getDirector())) return false;
      if (getReleaseYear()
          != other.getReleaseYear()) return false;
      if (!getGenreList()
          .equals(other.getGenreList())) return false;
      if (!getRating()
          .equals(other.getRating())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getCastList()
          .equals(other.getCastList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMovieId());
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DIRECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getDirector().hashCode();
      hash = (37 * hash) + RELEASE_YEAR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReleaseYear());
      if (getGenreCount() > 0) {
        hash = (37 * hash) + GENRE_FIELD_NUMBER;
        hash = (53 * hash) + getGenreList().hashCode();
      }
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + getRating().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (getCastCount() > 0) {
        hash = (37 * hash) + CAST_FIELD_NUMBER;
        hash = (53 * hash) + getCastList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.MovieDetailsProto.MovieDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protos.MovieDetailsProto.MovieDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protos.MovieDetailsProto.MovieDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.MovieDetailsProto.MovieDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.MovieDetailsProto.MovieDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.MovieDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.MovieDetails)
        protos.MovieDetailsProto.MovieDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.MovieDetailsProto.internal_static_protos_MovieDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.MovieDetailsProto.internal_static_protos_MovieDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.MovieDetailsProto.MovieDetails.class, protos.MovieDetailsProto.MovieDetails.Builder.class);
      }

      // Construct using protos.MovieDetailsProto.MovieDetails.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        movieId_ = 0L;
        title_ = "";
        director_ = "";
        releaseYear_ = 0L;
        genre_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        rating_ = "";
        description_ = "";
        if (castBuilder_ == null) {
          cast_ = java.util.Collections.emptyList();
        } else {
          cast_ = null;
          castBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.MovieDetailsProto.internal_static_protos_MovieDetails_descriptor;
      }

      @java.lang.Override
      public protos.MovieDetailsProto.MovieDetails getDefaultInstanceForType() {
        return protos.MovieDetailsProto.MovieDetails.getDefaultInstance();
      }

      @java.lang.Override
      public protos.MovieDetailsProto.MovieDetails build() {
        protos.MovieDetailsProto.MovieDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.MovieDetailsProto.MovieDetails buildPartial() {
        protos.MovieDetailsProto.MovieDetails result = new protos.MovieDetailsProto.MovieDetails(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(protos.MovieDetailsProto.MovieDetails result) {
        if (castBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0)) {
            cast_ = java.util.Collections.unmodifiableList(cast_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.cast_ = cast_;
        } else {
          result.cast_ = castBuilder_.build();
        }
      }

      private void buildPartial0(protos.MovieDetailsProto.MovieDetails result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.movieId_ = movieId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.director_ = director_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.releaseYear_ = releaseYear_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          genre_.makeImmutable();
          result.genre_ = genre_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.rating_ = rating_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.description_ = description_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.MovieDetailsProto.MovieDetails) {
          return mergeFrom((protos.MovieDetailsProto.MovieDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.MovieDetailsProto.MovieDetails other) {
        if (other == protos.MovieDetailsProto.MovieDetails.getDefaultInstance()) return this;
        if (other.getMovieId() != 0L) {
          setMovieId(other.getMovieId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDirector().isEmpty()) {
          director_ = other.director_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getReleaseYear() != 0L) {
          setReleaseYear(other.getReleaseYear());
        }
        if (!other.genre_.isEmpty()) {
          if (genre_.isEmpty()) {
            genre_ = other.genre_;
            bitField0_ |= 0x00000010;
          } else {
            ensureGenreIsMutable();
            genre_.addAll(other.genre_);
          }
          onChanged();
        }
        if (!other.getRating().isEmpty()) {
          rating_ = other.rating_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (castBuilder_ == null) {
          if (!other.cast_.isEmpty()) {
            if (cast_.isEmpty()) {
              cast_ = other.cast_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureCastIsMutable();
              cast_.addAll(other.cast_);
            }
            onChanged();
          }
        } else {
          if (!other.cast_.isEmpty()) {
            if (castBuilder_.isEmpty()) {
              castBuilder_.dispose();
              castBuilder_ = null;
              cast_ = other.cast_;
              bitField0_ = (bitField0_ & ~0x00000080);
              castBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetCastFieldBuilder() : null;
            } else {
              castBuilder_.addAllMessages(other.cast_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                movieId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                director_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                releaseYear_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureGenreIsMutable();
                genre_.add(s);
                break;
              } // case 42
              case 50: {
                rating_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                protos.MovieDetailsProto.Cast m =
                    input.readMessage(
                        protos.MovieDetailsProto.Cast.parser(),
                        extensionRegistry);
                if (castBuilder_ == null) {
                  ensureCastIsMutable();
                  cast_.add(m);
                } else {
                  castBuilder_.addMessage(m);
                }
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long movieId_ ;
      /**
       * <code>int64 movieId = 1;</code>
       * @return The movieId.
       */
      @java.lang.Override
      public long getMovieId() {
        return movieId_;
      }
      /**
       * <code>int64 movieId = 1;</code>
       * @param value The movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieId(long value) {

        movieId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 movieId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMovieId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        movieId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object director_ = "";
      /**
       * <code>string director = 3;</code>
       * @return The director.
       */
      public java.lang.String getDirector() {
        java.lang.Object ref = director_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          director_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string director = 3;</code>
       * @return The bytes for director.
       */
      public com.google.protobuf.ByteString
          getDirectorBytes() {
        java.lang.Object ref = director_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          director_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string director = 3;</code>
       * @param value The director to set.
       * @return This builder for chaining.
       */
      public Builder setDirector(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        director_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string director = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirector() {
        director_ = getDefaultInstance().getDirector();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string director = 3;</code>
       * @param value The bytes for director to set.
       * @return This builder for chaining.
       */
      public Builder setDirectorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        director_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long releaseYear_ ;
      /**
       * <code>int64 release_year = 4;</code>
       * @return The releaseYear.
       */
      @java.lang.Override
      public long getReleaseYear() {
        return releaseYear_;
      }
      /**
       * <code>int64 release_year = 4;</code>
       * @param value The releaseYear to set.
       * @return This builder for chaining.
       */
      public Builder setReleaseYear(long value) {

        releaseYear_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 release_year = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReleaseYear() {
        bitField0_ = (bitField0_ & ~0x00000008);
        releaseYear_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList genre_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureGenreIsMutable() {
        if (!genre_.isModifiable()) {
          genre_ = new com.google.protobuf.LazyStringArrayList(genre_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @return A list containing the genre.
       */
      public com.google.protobuf.ProtocolStringList
          getGenreList() {
        genre_.makeImmutable();
        return genre_;
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @return The count of genre.
       */
      public int getGenreCount() {
        return genre_.size();
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @param index The index of the element to return.
       * @return The genre at the given index.
       */
      public java.lang.String getGenre(int index) {
        return genre_.get(index);
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the genre at the given index.
       */
      public com.google.protobuf.ByteString
          getGenreBytes(int index) {
        return genre_.getByteString(index);
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @param index The index to set the value at.
       * @param value The genre to set.
       * @return This builder for chaining.
       */
      public Builder setGenre(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureGenreIsMutable();
        genre_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @param value The genre to add.
       * @return This builder for chaining.
       */
      public Builder addGenre(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureGenreIsMutable();
        genre_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @param values The genre to add.
       * @return This builder for chaining.
       */
      public Builder addAllGenre(
          java.lang.Iterable<java.lang.String> values) {
        ensureGenreIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, genre_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenre() {
        genre_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string genre = 5;</code>
       * @param value The bytes of the genre to add.
       * @return This builder for chaining.
       */
      public Builder addGenreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureGenreIsMutable();
        genre_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object rating_ = "";
      /**
       * <code>string rating = 6;</code>
       * @return The rating.
       */
      public java.lang.String getRating() {
        java.lang.Object ref = rating_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rating_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rating = 6;</code>
       * @return The bytes for rating.
       */
      public com.google.protobuf.ByteString
          getRatingBytes() {
        java.lang.Object ref = rating_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rating_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rating = 6;</code>
       * @param value The rating to set.
       * @return This builder for chaining.
       */
      public Builder setRating(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rating_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string rating = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRating() {
        rating_ = getDefaultInstance().getRating();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string rating = 6;</code>
       * @param value The bytes for rating to set.
       * @return This builder for chaining.
       */
      public Builder setRatingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rating_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 7;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 7;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 7;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 7;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.util.List<protos.MovieDetailsProto.Cast> cast_ =
        java.util.Collections.emptyList();
      private void ensureCastIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          cast_ = new java.util.ArrayList<protos.MovieDetailsProto.Cast>(cast_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protos.MovieDetailsProto.Cast, protos.MovieDetailsProto.Cast.Builder, protos.MovieDetailsProto.CastOrBuilder> castBuilder_;

      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public java.util.List<protos.MovieDetailsProto.Cast> getCastList() {
        if (castBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cast_);
        } else {
          return castBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public int getCastCount() {
        if (castBuilder_ == null) {
          return cast_.size();
        } else {
          return castBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public protos.MovieDetailsProto.Cast getCast(int index) {
        if (castBuilder_ == null) {
          return cast_.get(index);
        } else {
          return castBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder setCast(
          int index, protos.MovieDetailsProto.Cast value) {
        if (castBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCastIsMutable();
          cast_.set(index, value);
          onChanged();
        } else {
          castBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder setCast(
          int index, protos.MovieDetailsProto.Cast.Builder builderForValue) {
        if (castBuilder_ == null) {
          ensureCastIsMutable();
          cast_.set(index, builderForValue.build());
          onChanged();
        } else {
          castBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder addCast(protos.MovieDetailsProto.Cast value) {
        if (castBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCastIsMutable();
          cast_.add(value);
          onChanged();
        } else {
          castBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder addCast(
          int index, protos.MovieDetailsProto.Cast value) {
        if (castBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCastIsMutable();
          cast_.add(index, value);
          onChanged();
        } else {
          castBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder addCast(
          protos.MovieDetailsProto.Cast.Builder builderForValue) {
        if (castBuilder_ == null) {
          ensureCastIsMutable();
          cast_.add(builderForValue.build());
          onChanged();
        } else {
          castBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder addCast(
          int index, protos.MovieDetailsProto.Cast.Builder builderForValue) {
        if (castBuilder_ == null) {
          ensureCastIsMutable();
          cast_.add(index, builderForValue.build());
          onChanged();
        } else {
          castBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder addAllCast(
          java.lang.Iterable<? extends protos.MovieDetailsProto.Cast> values) {
        if (castBuilder_ == null) {
          ensureCastIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cast_);
          onChanged();
        } else {
          castBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder clearCast() {
        if (castBuilder_ == null) {
          cast_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          castBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public Builder removeCast(int index) {
        if (castBuilder_ == null) {
          ensureCastIsMutable();
          cast_.remove(index);
          onChanged();
        } else {
          castBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public protos.MovieDetailsProto.Cast.Builder getCastBuilder(
          int index) {
        return internalGetCastFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public protos.MovieDetailsProto.CastOrBuilder getCastOrBuilder(
          int index) {
        if (castBuilder_ == null) {
          return cast_.get(index);  } else {
          return castBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public java.util.List<? extends protos.MovieDetailsProto.CastOrBuilder> 
           getCastOrBuilderList() {
        if (castBuilder_ != null) {
          return castBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cast_);
        }
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public protos.MovieDetailsProto.Cast.Builder addCastBuilder() {
        return internalGetCastFieldBuilder().addBuilder(
            protos.MovieDetailsProto.Cast.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public protos.MovieDetailsProto.Cast.Builder addCastBuilder(
          int index) {
        return internalGetCastFieldBuilder().addBuilder(
            index, protos.MovieDetailsProto.Cast.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.Cast cast = 8;</code>
       */
      public java.util.List<protos.MovieDetailsProto.Cast.Builder> 
           getCastBuilderList() {
        return internalGetCastFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protos.MovieDetailsProto.Cast, protos.MovieDetailsProto.Cast.Builder, protos.MovieDetailsProto.CastOrBuilder> 
          internalGetCastFieldBuilder() {
        if (castBuilder_ == null) {
          castBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protos.MovieDetailsProto.Cast, protos.MovieDetailsProto.Cast.Builder, protos.MovieDetailsProto.CastOrBuilder>(
                  cast_,
                  ((bitField0_ & 0x00000080) != 0),
                  getParentForChildren(),
                  isClean());
          cast_ = null;
        }
        return castBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protos.MovieDetails)
    }

    // @@protoc_insertion_point(class_scope:protos.MovieDetails)
    private static final protos.MovieDetailsProto.MovieDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.MovieDetailsProto.MovieDetails();
    }

    public static protos.MovieDetailsProto.MovieDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieDetails>
        PARSER = new com.google.protobuf.AbstractParser<MovieDetails>() {
      @java.lang.Override
      public MovieDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MovieDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.MovieDetailsProto.MovieDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CastOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.Cast)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string actor_name = 1;</code>
     * @return The actorName.
     */
    java.lang.String getActorName();
    /**
     * <code>string actor_name = 1;</code>
     * @return The bytes for actorName.
     */
    com.google.protobuf.ByteString
        getActorNameBytes();

    /**
     * <code>string character_name = 2;</code>
     * @return The characterName.
     */
    java.lang.String getCharacterName();
    /**
     * <code>string character_name = 2;</code>
     * @return The bytes for characterName.
     */
    com.google.protobuf.ByteString
        getCharacterNameBytes();
  }
  /**
   * Protobuf type {@code protos.Cast}
   */
  public static final class Cast extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.Cast)
      CastOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        Cast.class.getName());
    }
    // Use Cast.newBuilder() to construct.
    private Cast(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Cast() {
      actorName_ = "";
      characterName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.MovieDetailsProto.internal_static_protos_Cast_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.MovieDetailsProto.internal_static_protos_Cast_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.MovieDetailsProto.Cast.class, protos.MovieDetailsProto.Cast.Builder.class);
    }

    public static final int ACTOR_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object actorName_ = "";
    /**
     * <code>string actor_name = 1;</code>
     * @return The actorName.
     */
    @java.lang.Override
    public java.lang.String getActorName() {
      java.lang.Object ref = actorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorName_ = s;
        return s;
      }
    }
    /**
     * <code>string actor_name = 1;</code>
     * @return The bytes for actorName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActorNameBytes() {
      java.lang.Object ref = actorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHARACTER_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object characterName_ = "";
    /**
     * <code>string character_name = 2;</code>
     * @return The characterName.
     */
    @java.lang.Override
    public java.lang.String getCharacterName() {
      java.lang.Object ref = characterName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        characterName_ = s;
        return s;
      }
    }
    /**
     * <code>string character_name = 2;</code>
     * @return The bytes for characterName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCharacterNameBytes() {
      java.lang.Object ref = characterName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        characterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, actorName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(characterName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, characterName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, actorName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(characterName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, characterName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.MovieDetailsProto.Cast)) {
        return super.equals(obj);
      }
      protos.MovieDetailsProto.Cast other = (protos.MovieDetailsProto.Cast) obj;

      if (!getActorName()
          .equals(other.getActorName())) return false;
      if (!getCharacterName()
          .equals(other.getCharacterName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTOR_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getActorName().hashCode();
      hash = (37 * hash) + CHARACTER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCharacterName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.MovieDetailsProto.Cast parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protos.MovieDetailsProto.Cast parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protos.MovieDetailsProto.Cast parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protos.MovieDetailsProto.Cast parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.MovieDetailsProto.Cast prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.Cast}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.Cast)
        protos.MovieDetailsProto.CastOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.MovieDetailsProto.internal_static_protos_Cast_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.MovieDetailsProto.internal_static_protos_Cast_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.MovieDetailsProto.Cast.class, protos.MovieDetailsProto.Cast.Builder.class);
      }

      // Construct using protos.MovieDetailsProto.Cast.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        actorName_ = "";
        characterName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.MovieDetailsProto.internal_static_protos_Cast_descriptor;
      }

      @java.lang.Override
      public protos.MovieDetailsProto.Cast getDefaultInstanceForType() {
        return protos.MovieDetailsProto.Cast.getDefaultInstance();
      }

      @java.lang.Override
      public protos.MovieDetailsProto.Cast build() {
        protos.MovieDetailsProto.Cast result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.MovieDetailsProto.Cast buildPartial() {
        protos.MovieDetailsProto.Cast result = new protos.MovieDetailsProto.Cast(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protos.MovieDetailsProto.Cast result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.actorName_ = actorName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.characterName_ = characterName_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.MovieDetailsProto.Cast) {
          return mergeFrom((protos.MovieDetailsProto.Cast)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.MovieDetailsProto.Cast other) {
        if (other == protos.MovieDetailsProto.Cast.getDefaultInstance()) return this;
        if (!other.getActorName().isEmpty()) {
          actorName_ = other.actorName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCharacterName().isEmpty()) {
          characterName_ = other.characterName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                actorName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                characterName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object actorName_ = "";
      /**
       * <code>string actor_name = 1;</code>
       * @return The actorName.
       */
      public java.lang.String getActorName() {
        java.lang.Object ref = actorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          actorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string actor_name = 1;</code>
       * @return The bytes for actorName.
       */
      public com.google.protobuf.ByteString
          getActorNameBytes() {
        java.lang.Object ref = actorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actor_name = 1;</code>
       * @param value The actorName to set.
       * @return This builder for chaining.
       */
      public Builder setActorName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        actorName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string actor_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearActorName() {
        actorName_ = getDefaultInstance().getActorName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string actor_name = 1;</code>
       * @param value The bytes for actorName to set.
       * @return This builder for chaining.
       */
      public Builder setActorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        actorName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object characterName_ = "";
      /**
       * <code>string character_name = 2;</code>
       * @return The characterName.
       */
      public java.lang.String getCharacterName() {
        java.lang.Object ref = characterName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          characterName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string character_name = 2;</code>
       * @return The bytes for characterName.
       */
      public com.google.protobuf.ByteString
          getCharacterNameBytes() {
        java.lang.Object ref = characterName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          characterName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string character_name = 2;</code>
       * @param value The characterName to set.
       * @return This builder for chaining.
       */
      public Builder setCharacterName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        characterName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string character_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCharacterName() {
        characterName_ = getDefaultInstance().getCharacterName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string character_name = 2;</code>
       * @param value The bytes for characterName to set.
       * @return This builder for chaining.
       */
      public Builder setCharacterNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        characterName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.Cast)
    }

    // @@protoc_insertion_point(class_scope:protos.Cast)
    private static final protos.MovieDetailsProto.Cast DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.MovieDetailsProto.Cast();
    }

    public static protos.MovieDetailsProto.Cast getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cast>
        PARSER = new com.google.protobuf.AbstractParser<Cast>() {
      @java.lang.Override
      public Cast parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Cast> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cast> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.MovieDetailsProto.Cast getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_MovieDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_MovieDetails_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Cast_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_Cast_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023movie_details.proto\022\006protos\"\246\001\n\014MovieD" +
      "etails\022\017\n\007movieId\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\020" +
      "\n\010director\030\003 \001(\t\022\024\n\014release_year\030\004 \001(\003\022\r" +
      "\n\005genre\030\005 \003(\t\022\016\n\006rating\030\006 \001(\t\022\023\n\013descrip" +
      "tion\030\007 \001(\t\022\032\n\004cast\030\010 \003(\0132\014.protos.Cast\"2" +
      "\n\004Cast\022\022\n\nactor_name\030\001 \001(\t\022\026\n\016character_" +
      "name\030\002 \001(\t*`\n\005Genre\022\n\n\006ACTION\020\000\022\n\n\006COMED" +
      "Y\020\001\022\t\n\005DRAMA\020\002\022\n\n\006HORROR\020\003\022\013\n\007ROMANCE\020\004\022" +
      "\014\n\010THRILLER\020\005\022\r\n\tADVENTURE\020\006B\033\n\006protosB\021" +
      "MovieDetailsProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_MovieDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_MovieDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_MovieDetails_descriptor,
        new java.lang.String[] { "MovieId", "Title", "Director", "ReleaseYear", "Genre", "Rating", "Description", "Cast", });
    internal_static_protos_Cast_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_Cast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_Cast_descriptor,
        new java.lang.String[] { "ActorName", "CharacterName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
